<a href="https://colab.research.google.com/github/duggiralasravan/Skillfy_ML/blob/ML_Notes/EAD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import pandas as pd
import numpy as np

data = {'Name': ['Alice', 'Bob','Neha'], 'weight': [55, 70,np.nan],'age':[25,30,28]}
df = pd.DataFrame(data)
print(df)

    Name  weight  age
0  Alice    55.0   25
1    Bob    70.0   30
2   Neha     NaN   28

In [19]:
df['weight'] = df['weight'].fillna(df['weight'].mean())
df

    Name  weight  age
0  Alice    55.0   25
1    Bob    70.0   30
2   Neha    62.5   28

In [ ]:
# Scaling / Feature Scaling
# Bringing all the numeric features to a similar scale
# -> Standardization - Convert numbers so that they are measured related to the average, the mean becomes 0 and STD becomes 1(Z- Score)
# Z = (x-mean)/ Standard Deviation
# When to use - Normally distributted data (60,65,70,75,67,84)
# Algo : Linear Regression/Logistic Regression/KNN/K-Mean/PCA/SupportsDivMod
# -> Normalization

In [4]:
from sklearn.preprocessing import StandardScaler

In [20]:
std = StandardScaler()
df[['weight','age']] = std.fit_transform(df[['weight','age']])
df

    Name    weight       age
0  Alice -1.224745 -1.297771
1    Bob  1.224745  1.135550
2   Neha  0.000000  0.162221

## Normalization
# -> Fixed Range = 0 to 1
X_normalized = (x-min)/(max-min)
Not sensitive to outliers
When to used Normalization
-> Data is not normally distributed
- Alg0 - KNN/K -Mena/ Neural Networks

In [30]:
# Simpleimputor
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
df[['weight','age']] = imputer.fit_transform(df[['weight','age']])
df

    Name  weight   age
0  Alice    55.0  25.0
1    Bob    70.0  30.0
2   Neha    62.5  28.0

In [31]:
scaler = MinMaxScaler()
df[['weight','age']] = scaler.fit_transform(df[['weight','age']])
df.head()

    Name  weight  age
0  Alice     0.0  0.0
1    Bob     1.0  1.0
2   Neha     0.5  0.6

# Categorical Variables
# T-Shirt

1.   Color -> red,yellow,green,bluew,white
2.   Size -> XS,S,M,L,XL
3. Price -> 10,20,12,30

#### Two types of categorical variables
- Ordinal Categorical variables --> which can be ordered XS<S<M<L<XL
- Nominal Categorical variables --> Data which can't be ordered

In [41]:
import pandas as pd

# Data for the categorical example
colors = ['red', 'yellow', 'green', 'blue', 'white']
sizes = ['XS', 'S', 'S', 'L', 'L']
prices = [10, 20, 12, 30, 15] # Added an extra price to match length
class_data= ['class1','class2','class3','class1','class3']
# Create the DataFrame
clothing_df = pd.DataFrame({
    'Color': colors,
    'Size': sizes,
    'Price': prices,
    'Class': class_data
})

print(clothing_df)

    Color Size  Price   Class
0     red   XS     10  class1
1  yellow    S     20  class2
2   green    S     12  class3
3    blue    L     30  class1
4   white    L     15  class3

In [38]:
size_mapping = {'XS':0,'S':1,'M':2,'L':3,'XL':4}
clothing_df['Size'] = clothing_df['Size'].map(size_mapping)
clothing_df

    Color  Size  Price   Class
0     red     0     10  class1
1  yellow     1     20  class2
2   green     1     12  class3
3    blue     3     30  class1
4   white     3     15  class3

In [42]:
# Label Encoding (Ordinal Data)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
clothing_df['Size'] = le.fit_transform(clothing_df['Size'])
clothing_df

    Color  Size  Price   Class
0     red     2     10  class1
1  yellow     1     20  class2
2   green     1     12  class3
3    blue     0     30  class1
4   white     0     15  class3