<a href="https://colab.research.google.com/github/duggiralasravan/Skillfy_ML/blob/ML_Notes/EAD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np

data = {'Name': ['Alice', 'Bob','Neha'], 'weight': [55, 70,np.nan],'age':[25,30,28]}
df = pd.DataFrame(data)
print(df)

    Name  weight  age
0  Alice    55.0   25
1    Bob    70.0   30
2   Neha     NaN   28

In [19]:
df['weight'] = df['weight'].fillna(df['weight'].mean())
df

    Name  weight  age
0  Alice    55.0   25
1    Bob    70.0   30
2   Neha    62.5   28

In [ ]:
# Scaling / Feature Scaling
# Bringing all the numeric features to a similar scale
# -> Standardization - Convert numbers so that they are measured related to the average, the mean becomes 0 and STD becomes 1(Z- Score)
# Z = (x-mean)/ Standard Deviation
# When to use - Normally distributted data (60,65,70,75,67,84)
# Algo : Linear Regression/Logistic Regression/KNN/K-Mean/PCA/SupportsDivMod
# -> Normalization

In [4]:
from sklearn.preprocessing import StandardScaler

In [20]:
std = StandardScaler()
df[['weight','age']] = std.fit_transform(df[['weight','age']])
df

    Name    weight       age
0  Alice -1.224745 -1.297771
1    Bob  1.224745  1.135550
2   Neha  0.000000  0.162221

## Normalization
# -> Fixed Range = 0 to 1
X_normalized = (x-min)/(max-min)
Not sensitive to outliers
When to used Normalization
-> Data is not normally distributed
- Alg0 - KNN/K -Mena/ Neural Networks